### ISSUE TITLE
missing fucntools32 from prerequisites

### ISSUE THREAD

**Issue by akshatnair** [prestodb/tempto#100]
Update docs to include this,

$presto/presto-product-tests/etc/singlenode$ docker-compose up -d
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = `__import__`(self.module_name, globals(),globals(), [`'__name__'`])
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 18, in <module>
    from ..config import config
  File "/usr/local/lib/python2.7/dist-packages/compose/config/__init__.py", line 5, in <module>
    from .config import ConfigurationError
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 33, in <module>
    from .validation import match_named_volumes
  File "/usr/local/lib/python2.7/dist-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema.exceptions import (
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/exceptions.py", line 6, in <module>
    from jsonschema import _utils
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import str_types, MutableMapping, urlsplit
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/compat.py", line 39, in <module>
    from functools32 import lru_cache

**ImportError: No module named functools32**

**Comment by kokosing** [comment]
@akshatnair this is not a tempto issue, but presto. How did you installed docker-compose and what OS you are using?

**Comment by akshatnair** [comment]
@kokosing yes, I will close this and reopen it for Presto, thanks!
I installed it as per our docs, "pip install docker-compose"
This is Ubuntu 12.04
