### ISSUE TITLE
No detailed error message returned when missing configuration entry

### ISSUE THREAD

**Issue by kokosing** [prestodb/tempto#119]
When injecting to a test configuration entry:
```
@Inject
@Named("some.conf")
String someConf
```
which is given in cofiguration yaml files tempto return error message with no details in it.

```
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Optional.<init>(Optional.java:96)
        at java.util.Optional.of(Optional.java:108)
        at com.teradata.tempto.internal.configuration.MapConfiguration.getObject(MapConfiguration.java:87)
        at com.teradata.tempto.internal.configuration.MapConfiguration.get(MapConfiguration.java:77)
```

**Comment by kokosing** [comment]
It could be due missing value in configuration.
```
key:
key2: value
```
