### ISSUE TITLE
Support  @Test(singleThreaded = true)

### ISSUE THREAD

**Issue by kokosing** [prestodb/tempto#195]
Now when `@Test(singleThreaded = true)` is used tempto is failing with an exception that no tests are executed.

**Comment by kokosing** [comment]
The root case comes from`DataProviders` class.

```
Exception in thread "main" java.lang.NullPointerException
        at com.teradata.tempto.internal.DataProviders.getParametersForMethod(DataProviders.java:45)
        at com.teradata.tempto.internal.initialization.RequirementsExpanderInterceptor.incrementSeenMethodsCount(RequirementsExpanderInterceptor.java:87)
        at com.teradata.tempto.internal.initialization.RequirementsExpanderInterceptor.intercept(RequirementsExpanderInterceptor.java:75)
        at org.testng.TestRunner.intercept(TestRunner.java:777)
        at org.testng.TestRunner.privateRun(TestRunner.java:723)
        at org.testng.TestRunner.run(TestRunner.java:610)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
        at org.testng.SuiteRunner.run(SuiteRunner.java:289)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
        at org.testng.TestNG.runSuites(TestNG.java:1133)
        at org.testng.TestNG.run(TestNG.java:1104)
        at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:95)
        at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:68)
        at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:56)
        at com.facebook.presto.tests.TemptoProductTestRunner.main(TemptoProductTestRunner.java:30)
```
