### ISSUE TITLE
Tempto fails with TestNG 6.10

### ISSUE THREAD

**Issue by electrum** [prestodb/tempto#202]
```
java.lang.NoSuchMethodError: org.testng.xml.XmlTest.setParallel(Ljava/lang/String;)V
	at com.teradata.tempto.runner.TemptoRunner.getXmlSuite(TemptoRunner.java:136)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:85)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:68)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:56)
	at com.facebook.presto.tests.TemptoProductTestRunner.main(TemptoProductTestRunner.java:30)

**Comment by kokosing** [comment]
Fixed already with https://github.com/prestodb/tempto/commit/c7703669654203997a1776105665673890b0a22c
